#Allows L2DamageTracker to detect and prevent cyclic damage events
enableCyclicDamageEventInterrupt = false
#Cyclic Damage Interruption threshold
#Range: 1 ~ 1000
cyclicDamageThreshold = 1
#Mute error log lines for cyclic damage
muteCyclicDamageInterrupt = false
#Print damage trace tracked by damage tracker
printDamageTrace = false
#Save player attack damage trace
savePlayerAttack = false
#Save player hurt damage trace
savePlayerDamaged = false

