
[General]
	#Gives you the ami wiki book at start
	AMI_WIKI_ENABLED = true
	#Whether animals that target food recieve the effects of the food they grab
	FOOD_TARGET_EFFECTS_ENABLED = true
	#Pour lava bottles into mobs to combust them to flames
	MOLTEN_BATH_ENABLED = true
	#Pour poison bottles into mobs to poison them alike
	POISONOUS_BATH_ENABLED = true
	#Infinite ammo for pocket sand
	BOTTOMLESS_SAND_ENABLED = true
	#Add targets for mobs
	ADD_TARGETS_ENABLED = true
	#--Compatibility with Soul Fire--
	#Being oiled will cause you to combust more from 'hot' blocks
	COMBUSTABLE_ENABLED = true

[Mobs]

	[Mobs."Vanilla Mob Tweaks"]
		#Witch drinks poison resistance when poisoned
		WITCH_ADDITIONS_ENABLED = true
		#Frogs and Rain Frogs can be converted into a Warped Toad
		FROG_TRANSFORM_ENABLED = true

	[Mobs."Alligator Snapping Turtle"]
		#Snapping Turtles will be active at night or when raining and will remain dormant unless disturbed
		SNAPPING_DORMANCY_ENABLED = true
		#Snapping Turtles will rarely accumulate moss when raining or within water or grown by bonemealing watered turtles
		MOSS_PROPOGATION_ENABLED = true

	[Mobs.Anaconda]
		#Large Anacondas will rarely cannibalize on anacondas when 10% health or babies
		ANACONDA_CANNIBALIZE_ENABLED = true
		#Large Anacondas abandon their babies
		ORPHANED_ANACONDAS_ENABLED = true

	[Mobs."Bald Eagle"]
		#Bald Eagle will rarely cannibalize weaker eagles
		EAGLE_CANNIBALIZE_ENABLED = true
		#--Compatibility with Alexs Caves--
		#Bald Eagle can bomb targetted areas when being controlled
		BIRD_BOMBING_ENABLED = true

	[Mobs."Banana Slug"]
		#Banana Slugs can be lethally sheared for bananas
		BANANA_SHEAR_ENABLED = true

	[Mobs."Bone Serpent"]
		#Bone Serpents will fear Lavaithans due to their immense stature
		SERPENT_FEAR_ENABLED = true

	[Mobs.Bunfungus]
		#Bunfungus harvests carrots from crops
		CARROT_HARVESTING_ENABLED = true

	[Mobs.Caiman]
		#Caimans will attack players that are seen holding their eggs
		CAIMAN_EGG_ATTACK_ENABLED = true
		#Caimans will attack players now
		CAIMAN_AGGRO_ENABLED = true

	[Mobs."Capuchin Monkey"]
		#Capuchin Monkeys's darts can be applied with potions
		ANCIENT_EFFECTS_ENABLED = true

	[Mobs.Catfish]
		#Large Catfish will cannibalize on smaller catfish
		CATFISH_CANNIBALIZE_ENABLED = true
		#Catfish has a chance to inflicts poison to attackers
		CATFISH_VENOM_ENABLED = true

	[Mobs."Cave Centipede"]
		#--Compatibility with Curios Light--
		#Cave Centipedes fear light and players that hold light, They will attack if attacked
		LIGHT_FEAR_ENABLED = true

	[Mobs.Cockroach]
		#--Requires Alexs Caves--
		#Cockroaches will mutate into Gammaroaches from Alex's Caves when in the Toxic Caves (if the mod is present)
		COCKROACH_MUTATION_ENABLED = true
		#--Requires Alexs Caves--
		#Use a AC Game Controller,to convert an average cockroach into a god
		ASMONGOLD_ENABLED = true

	[Mobs.Cosmaw]
		#Cosmaws will get weak when they carry a heavy player, while weak, they cannot carry their owners at all
		COSMAW_WEAKENED_ENABLED = true

	[Mobs."Crimson Mosquito"]
		#Crimson Mosquitoes can be transformed into Warped Mosco by feeding warped muscle while weakened
		CRIMSON_TRANSFORM_ENABLED = true
		#Chance of crimson mosquitoes to spawn with blood inside them
		#Range: 0.0 ~ 1.0
		BLOODED_CHANCE = 0.2
		#Crimson Mosquitoes is immune to blood spits
		BLOOD_PROTECTION_ENABLED = true
		#Damage from blood spits is dependant from the source
		BLOOD_DAMAGE_DIFFERENCE_ENABLED = true
		#Crimson Mosquitoes with blood will pollinate nearby funguses
		FUNGUS_POLLINATE_ENABLED = true
		#--Compatibility with Biomes Of Plenty--
		#Blood spits will inflict you with the new 'Blooded' effect that causes temporary substantial weakness
		BLOODED_EFFECT_ENABLED = true

	[Mobs.Crocodile]
		#Crocodile has a halo when named 'Wally'
		EMOTIONAL_REMEMEMBRANCE_ENABLED = true

	[Mobs.Crow]
		#Crow will rarely eat their weaker selves unless if tamed
		CROW_CANNIBALIZE_ENABLED = true
		#Crows will not drop their weapons in their beak when attacked
		CROW_WARRIORS_ENABLED = true

	[Mobs.Elephant]
		#Tusked Elephants attack players when lingering long enough,unless holding Acacia Blossom
		ELEPHANT_TERRITORIAL_ENABLED = true
		#Tamed Elephants will trample small entities when ridden
		ELEPHANT_TRAMPLE_ENABLED = true

	[Mobs.Emu]
		#Emus will attack any that are seen with a ranged weapon
		RANGED_AGGRO_ENABLED = true
		#Emu will attack any that are seen holding their eggs
		EMU_EGG_ATTACK_ENABLED = true

	[Mobs.Enderiophage]
		#Enderiophage will attack any that are below 30% health
		INFECT_WEAK_ENABLED = true
		#Enderiophage will ignore any that have damage resistance, unless if attacked
		INFECT_IMMUNITY_ENABLED = true
		#Enderiophage when created will adapt to their dimension
		ENDERIOPHAGE_ADAPTION_ENABLED = true

	[Mobs.Endergrade]
		#Endergrade and its passengers are immune to the void
		VOIDED_ENDERGRADE_ENABLED = true

	[Mobs."Devils Hole Pupfish"]
		#Adds Trade for Fisherman with Devils Hole Pupfish 
		DEVILS_TRADE_ENABLED = true

	[Mobs.Farseer]
		#Farseer will discombobulate players when targeted,by scrambling their inventory and flashing them with illusions
		FARSEER_ALTERING_ENABLED = true
		#Farseer will attack any that are human-like
		FARSEER_HUMANLIKE_ATTACK_ENABLED = true

	[Mobs.Flutter]
		#Flutter can be fed a wither flower to be inflicted with withered
		FLUTTER_WITHERED_ENABLED = true
		#Flutter can be sheared for azalea and related
		FLUTTER_SHEAR_ENABLED = true
		#Flutters attract bees and hummingbirds
		FLOWERING_ATTRACTION_ENABLED = true

	[Mobs.Fly]
		#Flies will pester certain smelling animals
		FLY_PESTER_ENABLED = true
		#Lit candles will cause flies to run away from it
		CANDLE_REPEL_ENABLED = true
		#Hoflding a maggot while fishing will cause it to be consumed and increase luck for fishing
		MAGGOT_FISHING_ENABLED = true
		#--Requires Blooded Effect--
		#Flies can be transformed to Crimson Mosquitoes
		FLY_TRANSFORM_ENABLED = true

	[Mobs."Flying Fish"]
		#Flying Fish Boots's mechanics are changed to be more fluid and based on speed and look angle
		WEAVING_WATERS_ENABLED = true
		#Flying Fish can launch themselves when hurt
		PANIC_LAUNCING_ENABLED = true

	[Mobs."Frilled Shark"]
		#Frilled Shark will attack players with exsanguination or low on health
		BLEEDING_HUNGER_ENABLED = true

	[Mobs."Grizzly Bear"]
		#Grizzlies will not attack players when tamed
		GRIZZLY_PACIFIED_ENABLED = true
		#Grizzlies will turn to Freddy Fazbear when named such
		FREDDYABLE_ENABLED = true
		#Grizzlies that are pacified with honey can be brushed for hair
		BRUSHED_ENABLED = true
		#Grizzlies destroy containers containing food they like
		STORED_HUNGER_ENABLED = true
		#Grizzlies will hunt food when hadnt had honey for a while
		HONEYLESS_HUNTING_ENABLED = true

	[Mobs.Guster]
		#Gusters tornado effect strength is dependant on how light you are
		GUSTER_WEIGHT_ENABLED = true
		#Projectiles go through gusters (arrows,snowballs,etc..)
		GUSTER_PROJECTILE_PROT_ENABLED = true
		#Gusting is a new effect that causes inflicted to be immune to gusts and spawns gusts around players
		GUSTING_EFFECT_ENABLED = true

	[Mobs.Hummingbird]
		#Humming Birds pollinate only in the day
		POLINATE_DAY_ENABLED = true

	[Mobs.Kangaroo]
		#Kangaroos can be given totems
		PROPER_ARMAMENTS_ENABLED = true

	[Mobs."Komodo Dragon"]
		#Komodo Dragon is friendly towards players when tamed
		FRIENDLY_KOMODO_ENABLED = false

	[Mobs.Laviathan]
		#Obsidian Laviathans can be mined for obsidian, but will cause them slight harm
		OBSIDIAN_EXTRACT_ENABLED = true

	[Mobs."Leafcutter Ants"]
		#Leafcutter Chambers that are bustling with fungus can burst out cockroaches
		COCKROACH_CHAMBER_ENABLED = true
		#Leafcutter ants inflict quick poisons at hit
		ACIDIC_LEAFCUTTER_ENABLED = true
		#Whether leafcutter pupi is throwable that places anthills like normal
		THROWABLE_PUPI_ENABLED = true
		#Leafcutters have variants which also causes rivalry
		LEAFCUTTER_VARIANTS_ENABLED = true

	[Mobs.Lobster]
		#Lobster will only spawn at night
		LOBSTER_NIGHT_ENABLED = true

	[Mobs."Mantis Shrimp"]
		#Mantis Shrimp will cannibalize on low health mantis shrimp
		MANTIS_CANNIBALIZE_ENABLED = true
		#Mantis will attack players, unless if holding tropical fish
		MANTIS_AGGRO_ENABLED = true

	[Mobs.Mimicube]
		#Mimicubes attempt to mimic targetted player chats
		MIMICKRY_ENABLED = true

	[Mobs.Murmur]
		#Murmurs can regrow their head and its health is seperated from the main body
		MURMUR_REGROW_ENABLED = true
		#Tendon Whip can pickup items and xp as it moves for its owner, with the new 'Stretchy Accumulation' enchantment
		TENDON_GRAB_ENABLED = true
		#Unsettling Kimono will cause mobs that attack monsters to attack its wearer
		UNSETTLING_BACKFIRE_ENABLED = true

	[Mobs.Orca]
		#Orca's Might can provide temporary neutrality with skelewags
		MIGHT_UPGRADE_ENABLED = true

	[Mobs.Potoo]
		#Potoo give their holder temp night vision when dark enough
		POTOO_VISION_ENABLED = true

	[Mobs."Rain Frog"]
		#Rainfrogs burrow away when threatened
		BURROW_AWAY_ENABLED = true

	[Mobs.Rattlesnake]
		#Rattlesnake will cannibalize on weaker snakes
		RATTLESNAKE_CANNIBALIZE_ENABLED = true
		#Rattlesnakes are territorial against other snakes
		RATTLESNAKE_TERRITORIAL_ENABLED = true

	[Mobs.Rhino]
		#Adult rhinos will rarely accidentally attack baby rhinos
		ACCIDENTAL_BETRAYAL_ENABLED = true

	[Mobs.Roadrunner]
		#Roadrunners will only hunt at day
		ROADRUNNER_DAY_ENABLED = true

	[Mobs."Rocky Roller"]
		#Rolling Thunder allows the player to roll in liquid with the new enchantment 'Rolling Thunder'
		ROLLING_THUNDER_ENABLED = true

	[Mobs.Seagull]
		#Sombreros can prevent seagulls from stealing food from you
		SOMBRERO_PROTECTION_ENABLED = true
		#Seagulls below 40% health will not steal food
		SEAGULL_WEAKEN_ENABLED = true
		#Seagulls will only snatch food from your main or off hand
		HELD_FOOD_ENABLED = false

	[Mobs.Skelewag]
		#Skelewag circle their prey like hammerhead sharks
		SKELEWAG_CIRCLE_ENABLED = true
		#Withered Variant of Skelewag that can be made with coal
		WITHERED_SKELEWAG_ENABLED = true

	[Mobs.Skreecher]
		#Skreecher souls can be used on a Screacher block to allow it to spawn wardens
		SKREECHER_WARD_ENABLED = true
		#New potion effect that spawns a Warden on the player's position when it is about to ware off
		SKREECH_YOUR_LAST_ENABLED = true

	[Mobs."Snow Leopard"]
		#Snow Leopard can cause certain animals to drop certain items related to the prey
		SNOW_LUCK_ENABLED = true
		#Snow Leopard will hunt weaker moose, but will also mistakenly hunt players with moose headgear
		LEOPARD_DESIRES_ENABLED = true

	[Mobs."Soul Vulture"]
		#Soul Vultures no matter what, when attacking a mob will cause its level to go up
		VULTURE_STEAL_ENABLED = true

	[Mobs.Straddler]
		#Straddlers have ammo,once exhausted it requires time to reload (O Disables this feature)
		#Range: > 0
		STRADDLER_SHOTS_AMOUNT = 8
		#Straddleboards drop half of its material costs if it doesnt drop itself
		STRADDLE_SCAVENGE_ENABLED = true

	[Mobs.Stradpole]
		#Stradpole can be seen bobbing up or hopping in lava
		STRADPOLE_BOB_UP_ENABLED = true
		#Stradpole have a chance to inflict flame when launcher by straddlers
		STRADPOLE_FLAME_ENABLED = true

	[Mobs."Sugar Glider"]
		#Sugar Gliders can be speed up with sugar
		SUGAR_RUSH_ENABLED = true

	[Mobs.Sunbird]
		#Sun Bird Effects are changed for the better and the worst
		SUNBIRD_UPGRADE_ENABLED = true

	[Mobs.Terrapin]
		#Terrapin take damage when they get launched
		TERRAPIN_STOMP_ENABLED = true
		#Blue Shell Terrapin
		BLUE_SHELL_ENABLED = true

	[Mobs.Tiger]
		#Tigers Blessing will give invisibility when moving in a normal pace
		TIGER_STEALTH_ENABLED = true

	[Mobs.Tusklin]
		#Tusklins like their brethren flee from warped fungus
		TUSKLIN_FLEE_ENABLED = true
		#Tusklins can have a lasting trust with mushroom stew,attacking it will remove that lasting trust however
		TUSKLIN_TRUST_ENABLED = true
		#Tusklin struck by lightning will be converted to zoglins
		ZOGLINNED_ENABLED = true

	[Mobs."Void Worm"]
		#Void Worm can be stunned and brought down when hit in the head enough
		VOIDWORM_STUN_ENABLED = true
		#Dimensional Carver can be used to make a portal to a linked lodestone when holding the compass off-hand
		DIMENSIONAL_LODESTONE_ENABLED = true
		#Dimensional Carver speeds up with haste
		HASTY_CARVING_ENABLED = true

	[Mobs."Warped Mosco"]
		#Warped Mosco rarely cannibalize on Crimson Mosquitoes
		MOSCO_CANNIBALISM_ENABLED = true

	[Mobs."Warped Toad"]
		#Warped Toads will not attack food unless given the orders so
		WARPED_FRIENDLY_ENABLED = true

["April Fools"]
	#April Fools Banana Slug and Banana Effects
	GOOFY_BANANA_SLIP_ENABLED = false
	#April Fools Murmur Effects
	GOOFY_MURMUR_DECAPITATED_ENABLED = false
	#April Fools Crimson Mosquito Effects
	GOOFY_CRIMSON_MULTIPLY_ENABLED = false
	#April Fools Rain Frog Effects
	GOOFY_RAINFROG_SPAWNAGE_ENABLED = false
	#April Fools Capuchin Monkey Effects
	GOOFY_CAPUCHIN_BOMB_ENABLED = false
	#April Fools Straddler Effects
	GOOFY_STRADDLER_SHOTGUN_ENABLED = false
	#Boxing Gloves
	BOXING_GLOVES_ENABLED = false
	#Catfish texture changes when hot thing in mouth
	GOOFY_HOT_CAT_ENABLED = false

