
[Season]
#The lasting days of each term, while 4 seasons in 1 year, 6 terms in 1 season.
#Range: 1 ~ 5000
LastingDaysOfEachTerm = 7
#The index of the initial solar term, and note it only can be used to first start the world with the mod.
#Range: 1 ~ 24
InitialSolarTermIndex = 13
#Enable solar term change inform.
EnableInform = true
#Whether send inform with icon.
EnableInformIcon = true
#Enable local calendar and local info synchronization.
EnableLocalInfoAndCalendar = false
#Whether to pop up the solar term reminder when the calendar item cannot be placed.
CalendarItemHint = false
#In summer, the days are long and the nights are short, while in winter, the days are short and the nights are long.
DynamicDaylightDuration = true
#Day time length of spring, divided into six periods according to the solar term table.
SpringDayTimes = [10500, 11000, 11500, 12000, 12500, 13000]
#Day time length of summer, divided into six periods according to the solar term table.
SummerDayTimes = [13500, 14000, 14500, 15000, 14500, 14000]
#Day time length of autumn, divided into six periods according to the solar term table.
AutumnDayTimes = [13500, 13000, 12500, 12000, 11500, 11000]
#Day time length of winter, divided into six periods according to the solar term table.
WinterDayTimes = [10500, 10000, 9500, 9000, 9500, 10000]
#Day time length of none season, divided into six periods according to the solar term table.
NoneDayTimes = [12000]
#List of dimensions where season effects apply. Must be natural worlds with a day-night cycle.
ValidDimensions = [
	"minecraft:overworld",
	"minecraft:the_nether",
	"minecraft:the_end",
	"twilightforest:twilight_forest",
	"aether:the_aether",
]
#If snow falls during cold weather, it will gradually cover all solid blocks and grass.
SnowyWinter = true
#Not just the top layer, now even the leaves below are dusted with frost and snow.
SnowyTree = true
#Snow will not appear in overly bright areas, here define restriction levels.
NotSnowyNearGlowingBlock = true
#Snow will not appear in overly bright areas.
#Range: 1 ~ 15
NotSnowyNearGlowingBlockLevel = 10
#Specify block IDs here to prevent those blocks from being covered by snow.
ForceBlocksNotSnowy = []

[Weather]
#Enable solar term weather system with biome.
UseSolarWeather = true
#Set it true to initialize weather and snow when loading the mod or level for the first time.
ShouldInitWeather = false
#Multiplier (0-1000) affecting how likely rain will occur.
#Range: 0 ~ 1000
RainChancePercentMultiplier = 120
#Multiplier (0-1000) affecting how likely thunder will occur.
#Range: 0 ~ 1000
ThunderChancePercentMultiplier = 60

[Temperature]
#Ice or snow layer will melt in warm time.
IceAndSnowMelt = true
#It will snow in cold time.
IceAndSnow = true
#Add heat stroke effect in summer noon while in hot biome.
HeatStroke = true

[Crop]
#Enable crop season control.
EnableSeasonalCrop = true
#[Deprecated]How much chance can crop grow in wrong season.
#Range: 0.0 ~ 1.0
CropGrowChanceInWrongSeason = 0.15
#Enable crop humidity control.
EnableCropHumidityControl = true
#[Deprecated]How much base chance can crop grow in wrong humidity.
#Range: 1.0E-4 ~ 0.9999
CropGrowChanceInWrongHumidity = 0.5
#Send message to player if failed to use bone meal on crop.
BoneMealFailureMessage = true
#Consume anyway if failed to use bone meal on crop.
BoneMealConsumeOnFailure = true
#The maximum effective diameter of the greenhouse.
#Range: 5 ~ 256
GreenHouseMaxDiameter = 48
#The maximum effective diameter of the greenhouse.
#Range: 3 ~ 128
GreenHouseMaxHeight = 10
#Chance that crops fail to grow due to low sunlight inside the greenhouse.
#Range: 0 ~ 10000
DarkGreenhouseFailChance = 2000
#Build a simple greenhouse without core blocks and humidity modifiers.
SimpleGreenHouseMode = false
#If true, the Humidifier block will no longer consume blocks during conversion.
NoCostHumidifier = false
#The working range of the Season Core block.
#Range: 4 ~ 31
SeasonCoreRange = 15
#Whether to enable complex shape checking.
ComplexGreenHouseCheck = true
#Calculate the working range of the greenhouse block by box distance and not Euclidean range.
UseBoxDistance = true
#[Deprecated]If a crop is not registered for a season or humid type, default values will be used.
RegisterCropDefaultValue = false
#Force all crops to use compatibility mode for growth control, not just those tagged as eclipticseasons:natural_plants.
ForceCompatMode = false

[Compat]
#Compatible with mods using SereneSeasons' CropTag.
SereneSeasonsCropTag = true

[Debug]
#Enable debug option to detect illegal use of functions.
LogIllegalUse = false
#Disable snowy blocks beneath light sources with light level 0.
NotSnowyUnderLight0 = false
#Snow overlay block if has full collision shape not just full render shape.
SnowyFullCollisionShape = false
#Snow can cover the block which would lights.
NotSnowOverlayGlowingBlock = false

[Map]
#The map color of blocks will change during snow.
ChangeMapColor = true

[Resource]
#Enable extra built-in snow definitions resourcepack for game.
ExtraSnowDefinitions = false
