
#工匠砧显示的配置
["工匠砧显示"]
	#是否隐藏工匠砧界面的盔甲架，默认false
	DisableRenderArmorStand = false
	#是否在工具太多时为工匠站添加滚动条，默认false
	enableScrollingBar = false
	#在工具有多少行后才添加滚动条，默认8
	#Range: > 0
	ScrollingRollsThreshold = 8

