
[vanilla]

	[vanilla.axolotl]
		#Ingredients required for axolotl breeding
		axolotlIngredients = "minecraft:tropical_fish_bucket"
		axolotlSpawnEgg = "minecraft:axolotl_spawn_egg"
		axolotlBreedingCooldown = 6000

	[vanilla.bee]
		#Ingredients required for bee breeding
		beeIngredients = "#minecraft:flowers"
		beeSpawnEgg = "minecraft:bee_spawn_egg"
		beeBreedingCooldown = 6000

	[vanilla.camel]
		#Ingredients required for camel breeding
		camelIngredients = "minecraft:cactus"
		camelSpawnEgg = "minecraft:camel_spawn_egg"
		camelBreedingCooldown = 6000

	[vanilla.cat]
		#Ingredients required for cat breeding
		catIngredients = "minecraft:cod, minecraft:salmon"
		catSpawnEgg = "minecraft:cat_spawn_egg"
		catBreedingCooldown = 6000
		#Ingredients required for cat taming
		catTamingIngredients = "minecraft:cod, minecraft:salmon"
		#Range: 0 ~ 100
		catTamingChance = 33

	[vanilla.chicken]
		#Ingredients required for chicken breeding
		chickenIngredients = "minecraft:wheat_seeds, minecraft:pumpkin_seeds, minecraft:melon_seeds, minecraft:beetroot_seeds, minecraft:torchflower_seeds, minecraft:pitcher_pod"
		chickenSpawnEgg = "minecraft:chicken_spawn_egg"
		chickenBreedingCooldown = 6000

	[vanilla.cow]
		#Ingredients required for cow breeding
		cowIngredients = "minecraft:wheat"
		cowSpawnEgg = "minecraft:cow_spawn_egg"
		cowBreedingCooldown = 6000

	[vanilla.donkey]
		#Ingredients required for donkey breeding
		donkeyIngredients = "minecraft:golden_apple, minecraft:enchanted_golden_apple, minecraft:golden_carrot"
		donkeySpawnEgg = "minecraft:donkey_spawn_egg"
		donkeyBreedingCooldown = 6000
		#Ingredients that increase donkey temper
		donkeyTemperIngredients = "minecraft:sugar, minecraft:wheat, minecraft:apple, minecraft:golden_carrot, minecraft:golden_apple, minecraft:enchanted_golden_apple"
		#Values of ingredients that increase donkey temper
		donkeyTemperValues = "3, 3, 3, 5, 10, 10"

	[vanilla.fox]
		#Ingredients required for fox breeding
		foxIngredients = "#minecraft:fox_food"
		foxSpawnEgg = "minecraft:fox_spawn_egg"
		foxBreedingCooldown = 6000
		#Ingredients required for fox trusting
		foxTrustingIngredients = "#minecraft:fox_food"
		#Range: 0 ~ 100
		foxTrustingChance = 33

	[vanilla.frog]
		#Ingredients required for frog breeding
		frogIngredients = "minecraft:slime_ball"
		frogSpawnEgg = "minecraft:frog_spawn_egg"
		frogBreedingCooldown = 6000
		#Egg that frog lays after breeding
		frogEggResult = "minecraft:frogspawn"
		#Min amount of eggs that frog lays after breeding
		#Range: 1 ~ 64
		frogEggMinAmount = 1
		#Max amount of eggs that frog lays after breeding
		#Range: 1 ~ 64
		frogEggMaxAmount = 1

	[vanilla.goat]
		#Ingredients required for goat breeding
		goatIngredients = "minecraft:wheat"
		goatSpawnEgg = "minecraft:goat_spawn_egg"
		goatBreedingCooldown = 6000

	[vanilla.hoglin]
		#Ingredients required for hoglin breeding
		hoglinIngredients = "minecraft:crimson_fungus"
		hoglinSpawnEgg = "minecraft:hoglin_spawn_egg"
		hoglinBreedingCooldown = 6000

	[vanilla.horse]
		#Ingredients required for horse breeding
		horseIngredients = "minecraft:golden_apple, minecraft:enchanted_golden_apple, minecraft:golden_carrot"
		horseSpawnEgg = "minecraft:horse_spawn_egg"
		horseBreedingCooldown = 6000
		#Ingredients that increase horse temper
		horseTemperIngredients = "minecraft:sugar, minecraft:wheat, minecraft:apple, minecraft:golden_carrot, minecraft:golden_apple, minecraft:enchanted_golden_apple"
		#Values of ingredients that increase horse temper
		horseTemperValues = "3, 3, 3, 5, 10, 10"

	[vanilla.llama]
		#Ingredients required for llama breeding
		llamaIngredients = "minecraft:wheat, minecraft:hay_block"
		llamaSpawnEgg = "minecraft:llama_spawn_egg"
		llamaBreedingCooldown = 6000
		#Ingredients that increase llama temper
		llamaTemperIngredients = "minecraft:wheat, minecraft:hay_block"
		#Values of ingredients that increase llama temper
		llamaTemperValues = "3, 6"

	[vanilla.mooshroom]
		#Ingredients required for mooshroom breeding
		mooshroomIngredients = "minecraft:wheat"
		mooshroomSpawnEgg = "minecraft:mooshroom_spawn_egg"
		mooshroomBreedingCooldown = 6000

	[vanilla.ocelot]
		#Ingredients required for ocelot breeding
		ocelotIngredients = "minecraft:cod, minecraft:salmon"
		ocelotSpawnEgg = "minecraft:ocelot_spawn_egg"
		ocelotBreedingCooldown = 6000
		#Ingredients required for ocelot trusting
		ocelotTrustingIngredients = "minecraft:cod, minecraft:salmon"
		#Range: 0 ~ 100
		ocelotTrustingChance = 33

	[vanilla.panda]
		#Ingredients required for panda breeding
		pandaIngredients = "minecraft:bamboo"
		pandaSpawnEgg = "minecraft:panda_spawn_egg"
		pandaBreedingCooldown = 6000

	[vanilla.pig]
		#Ingredients required for pig breeding
		pigIngredients = "minecraft:carrot, minecraft:potato, minecraft:beetroot"
		pigSpawnEgg = "minecraft:pig_spawn_egg"
		pigBreedingCooldown = 6000

	[vanilla.rabbit]
		#Ingredients required for rabbit breeding
		rabbitIngredients = "minecraft:dandelion, minecraft:carrot, minecraft:golden_carrot"
		rabbitSpawnEgg = "minecraft:rabbit_spawn_egg"
		rabbitBreedingCooldown = 6000

	[vanilla.sheep]
		#Ingredients required for sheep breeding
		sheepIngredients = "minecraft:wheat"
		sheepSpawnEgg = "minecraft:sheep_spawn_egg"
		sheepBreedingCooldown = 6000

	[vanilla.sniffer]
		#Ingredients required for sniffer breeding
		snifferIngredients = "minecraft:torchflower_seeds"
		snifferSpawnEgg = "minecraft:sniffer_spawn_egg"
		snifferBreedingCooldown = 6000
		#Egg that sniffer lays after breeding
		snifferEggResult = "minecraft:sniffer_egg"
		#Min amount of eggs that sniffer lays after breeding
		#Range: 1 ~ 64
		snifferEggMinAmount = 1
		#Max amount of eggs that sniffer lays after breeding
		#Range: 1 ~ 64
		snifferEggMaxAmount = 1

	[vanilla.strider]
		#Ingredients required for strider breeding
		striderIngredients = "minecraft:warped_fungus"
		striderSpawnEgg = "minecraft:strider_spawn_egg"
		striderBreedingCooldown = 6000

	[vanilla.trader_llama]
		#Ingredients required for trader_llama breeding
		trader_llamaIngredients = "minecraft:wheat, minecraft:hay_block"
		trader_llamaSpawnEgg = "minecraft:trader_llama_spawn_egg"
		trader_llamaBreedingCooldown = 6000
		#Ingredients that increase trader_llama temper
		trader_llamaTemperIngredients = "minecraft:wheat, minecraft:hay_block"
		#Values of ingredients that increase trader_llama temper
		trader_llamaTemperValues = "3, 6"

	[vanilla.turtle]
		#Ingredients required for turtle breeding
		turtleIngredients = "minecraft:seagrass"
		turtleSpawnEgg = "minecraft:turtle_spawn_egg"
		turtleBreedingCooldown = 6000
		#Egg that turtle lays after breeding
		turtleEggResult = "minecraft:turtle_egg"
		#Min amount of eggs that turtle lays after breeding
		#Range: 1 ~ 64
		turtleEggMinAmount = 1
		#Max amount of eggs that turtle lays after breeding
		#Range: 1 ~ 64
		turtleEggMaxAmount = 4

	[vanilla.wolf]
		#Ingredients required for wolf breeding
		wolfIngredients = "minecraft:porkchop, minecraft:cooked_porkchop, minecraft:beef, minecraft:cooked_beef, minecraft:chicken, minecraft:cooked_chicken, minecraft:rotten_flesh, minecraft:rabbit, minecraft:cooked_rabbit, minecraft:mutton, minecraft:cooked_mutton"
		wolfSpawnEgg = "minecraft:wolf_spawn_egg"
		wolfBreedingCooldown = 6000
		#Ingredients required for wolf taming
		wolfTamingIngredients = "minecraft:bone"
		#Range: 0 ~ 100
		wolfTamingChance = 33

	[vanilla.mule]
		#Ingredients required for mule taming
		muleTamingIngredients = "minecraft:wheat, minecraft:hay_block"
		#Range: 0 ~ 100
		muleTamingChance = 33
		muleSpawnEgg = "minecraft:mule_spawn_egg"
		#Ingredients that increase mule temper
		muleTemperIngredients = "minecraft:sugar, minecraft:wheat, minecraft:apple, minecraft:golden_carrot, minecraft:golden_apple, minecraft:enchanted_golden_apple"
		#Values of ingredients that increase mule temper
		muleTemperValues = "3, 3, 3, 5, 10, 10"

	[vanilla.parrot]
		#Ingredients required for parrot taming
		parrotTamingIngredients = "minecraft:wheat_seeds, minecraft:pumpkin_seeds, minecraft:melon_seeds, minecraft:beetroot_seeds, minecraft:torchflower_seeds, minecraft:pitcher_pod"
		#Range: 0 ~ 100
		parrotTamingChance = 33
		parrotSpawnEgg = "minecraft:parrot_spawn_egg"

	[vanilla.allay]
		#Ingredients required for allay trusting
		allayTrustingIngredients = "*"
		#Range: 0 ~ 100
		allayTrustingChance = 33
		allaySpawnEgg = "minecraft:allay_spawn_egg"

[integration]

	[integration.twilightforest]

		[integration.twilightforest.bighorn_sheep]
			#Ingredients required for bighorn_sheep breeding
			bighorn_sheepIngredients = "minecraft:wheat"
			bighorn_sheepSpawnEgg = "twilightforest:bighorn_sheep_spawn_egg"
			bighorn_sheepBreedingCooldown = 6000

		[integration.twilightforest.boar]
			#Ingredients required for boar breeding
			boarIngredients = "minecraft:carrot, minecraft:potato, minecraft:beetroot"
			boarSpawnEgg = "twilightforest:boar_spawn_egg"
			boarBreedingCooldown = 6000

		[integration.twilightforest.deer]
			#Ingredients required for deer breeding
			deerIngredients = "minecraft:wheat"
			deerSpawnEgg = "twilightforest:deer_spawn_egg"
			deerBreedingCooldown = 6000

		[integration.twilightforest.dwarf_rabbit]
			#Ingredients required for dwarf_rabbit breeding
			dwarf_rabbitIngredients = "minecraft:dandelion, minecraft:carrot, minecraft:golden_carrot"
			dwarf_rabbitSpawnEgg = "twilightforest:dwarf_rabbit_spawn_egg"
			dwarf_rabbitBreedingCooldown = 6000

		[integration.twilightforest.penguin]
			#Ingredients required for penguin breeding
			penguinIngredients = "minecraft:cod"
			penguinSpawnEgg = "twilightforest:penguin_spawn_egg"
			penguinBreedingCooldown = 6000

	[integration.alexscaves]

		[integration.alexscaves.relicheirus]
			#Ingredients required for relicheirus breeding
			relicheirusIngredients = "alexscaves:tree_star"
			relicheirusSpawnEgg = "alexscaves:spawn_egg_relicheirus"
			relicheirusBreedingCooldown = 6000
			#Egg that relicheirus lays after breeding
			relicheirusEggResult = "alexscaves:relicheirus_egg"
			#Min amount of eggs that relicheirus lays after breeding
			#Range: 1 ~ 64
			relicheirusEggMinAmount = 1
			#Max amount of eggs that relicheirus lays after breeding
			#Range: 1 ~ 64
			relicheirusEggMaxAmount = 1

		[integration.alexscaves.subterranodon]
			#Ingredients required for subterranodon breeding
			subterranodonIngredients = "minecraft:cod, minecraft:cooked_cod"
			subterranodonSpawnEgg = "alexscaves:spawn_egg_subterranodon"
			subterranodonBreedingCooldown = 6000
			#Egg that subterranodon lays after breeding
			subterranodonEggResult = "alexscaves:subterranodon_egg"
			#Min amount of eggs that subterranodon lays after breeding
			#Range: 1 ~ 64
			subterranodonEggMinAmount = 1
			#Max amount of eggs that subterranodon lays after breeding
			#Range: 1 ~ 64
			subterranodonEggMaxAmount = 4

		[integration.alexscaves.tremorsaurus]
			#Ingredients required for tremorsaurus breeding
			tremorsaurusIngredients = "alexscaves:cooked_dinosaur_chop, alexscaves:dinosaur_chop"
			tremorsaurusSpawnEgg = "alexscaves:spawn_egg_tremorsaurus"
			tremorsaurusBreedingCooldown = 6000
			#Egg that tremorsaurus lays after breeding
			tremorsaurusEggResult = "alexscaves:tremorsaurus_egg"
			#Min amount of eggs that tremorsaurus lays after breeding
			#Range: 1 ~ 64
			tremorsaurusEggMinAmount = 1
			#Max amount of eggs that tremorsaurus lays after breeding
			#Range: 1 ~ 64
			tremorsaurusEggMaxAmount = 1
			#Ingredients required for tremorsaurus taming
			tremorsaurusTamingIngredients = "alexscaves:serene_salad"
			#Range: 0 ~ 100
			tremorsaurusTamingChance = 33
			#Extra ingredients required for tremorsaurus taming
			tremorsaurusExtraTamingIngredients = "alexscaves:primitive_club"

		[integration.alexscaves.vallumraptor]
			#Ingredients required for vallumraptor breeding
			vallumraptorIngredients = "alexscaves:dinosaur_nugget"
			vallumraptorSpawnEgg = "alexscaves:spawn_egg_vallumraptor"
			vallumraptorBreedingCooldown = 6000
			#Egg that vallumraptor lays after breeding
			vallumraptorEggResult = "alexscaves:vallumraptor_egg"
			#Min amount of eggs that vallumraptor lays after breeding
			#Range: 1 ~ 64
			vallumraptorEggMinAmount = 1
			#Max amount of eggs that vallumraptor lays after breeding
			#Range: 1 ~ 64
			vallumraptorEggMaxAmount = 4
			#Ingredients required for vallumraptor taming
			vallumraptorTamingIngredients = "alexscaves:serene_salad"
			#Range: 0 ~ 100
			vallumraptorTamingChance = 33

		[integration.alexscaves.raycat]
			#Ingredients required for raycat breeding
			raycatIngredients = "alexscaves:radgill"
			raycatSpawnEgg = "alexscaves:spawn_egg_raycat"
			raycatBreedingCooldown = 6000
			#Ingredients required for raycat taming
			raycatTamingIngredients = "alexscaves:radgill"
			#Range: 0 ~ 100
			raycatTamingChance = 33

