
[botania]

	[botania.mana_infusion]
		enable = true
		accept_by_default = false

	[botania.elven_trade]
		enable = true

	[botania.mythical_flower]
		enable = true

	[botania.pure_daisy]
		enable = true

	[botania.runic_altar]
		enable = true

	[botania.petal_apothecary]
		enable = true

[ars_nouveau]

	[ars_nouveau.imbuement]
		enable = true

	[ars_nouveau.enchantment]
		enable = true

	[ars_nouveau.enchanting_apparatus]
		enable = true

[maid_storage_manager]

	[maid_storage_manager.smithing]
		enable = true

	[maid_storage_manager.brewing]
		enable = true
		count = 3

	[maid_storage_manager.stripping]
		enable = true

	[maid_storage_manager.altar]
		enable = true

	[maid_storage_manager.furnace]
		enable = true

	[maid_storage_manager.watering]
		bucket = true
		enable = true
		bottle = true

	[maid_storage_manager.craft]
		enable = true

	[maid_storage_manager.stone_cutting]
		enable = true

[create]

	[create.crushing]
		enable = true
		count = 16

	[create.pressing]
		enable = true

	[create.fan]
		haunting = true
		splashing = true
		enable = true
		smoking = true
		count = 8
		replace_furnace = true
		blasting = true

	[create.compacting]
		enable = true

	[create.mixing]
		enable = true

	[create.deploying]
		enable = true

	[create.milling]
		enable = true

	[create.item_application]
		enable = true

[ae2]

	[ae2.charger]
		enable = true

	[ae2.inscriber]
		enable = true

	[ae2.item_transform]
		enable = true

