
[maid]
	#The item that can tamed maid
	#Use the registered name of the item directly or write tag name with # as prefix
	MaidTamedItem = "minecraft:cake"
	#The item that can temptation maid
	#Use the registered name of the item directly or write tag name with # as prefix
	MaidTemptationItem = "minecraft:cake"
	#The max range of maid work mode
	#Range: 3 ~ 64
	MaidWorkRange = 12
	#The max range of maid idle mode
	#Range: 3 ~ 32
	MaidIdleRange = 6
	#The max range of maid sleep mode
	#Range: 3 ~ 32
	MaidSleepRange = 6
	#The max range of maid's Non-Home mode
	#Range: 3 ~ 32
	MaidNonHomeRange = 8
	#The max number of animals around when the maid breeds animals
	#Range: 6 ~ 65536
	FeedAnimalMaxNumber = 50
	#Maid can switch models freely
	MaidChangeModel = true
	#Maid can only play gomoku with her owner
	MaidGomokuOwnerLimit = true
	#The maximum number of maids the player own
	#Range: > 0
	OwnerMaxMaidNum = 2147483647
	#These items cannot be placed in the maid backpack
	MaidBackpackBlackList = []
	#The entity that the maid will not recognize as targets for attack
	MaidAttackIgnore = []
	#The entity that the maid will not hurt when in ranged attack
	MaidRangedAttackIgnore = []
	#Percentage chance of replace Allays spawn in pillager outposts with Maids
	#Range: 0.0 ~ 1.0
	ReplaceAllayPercent = 0.2
	#These items cannot be used as a maid's work meals
	MaidWorkMealsBlockList = ["minecraft:pufferfish", "minecraft:poisonous_potato", "minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:chorus_fruit"]
	#These items cannot be used as a maid's home meals
	MaidHomeMealsBlockList = ["minecraft:pufferfish", "minecraft:poisonous_potato", "minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:chorus_fruit"]
	#These items cannot be used as a maid's heal meals
	MaidHealMealsBlockList = ["minecraft:pufferfish", "minecraft:poisonous_potato", "minecraft:rotten_flesh", "minecraft:spider_eye"]
	#These items cannot be used as a maid's work meals which match the regex
	MaidWorkMealsBlockListRegEx = []
	#These items cannot be used as a maid's home meals which match the regex
	MaidHomeMealsBlockListRegEx = []
	#These items cannot be used as a maid's heal meals which match the regex
	MaidHealMealsBlockListRegEx = []
	#These entries configure the container returned after a maid has eaten
	#Eg: ["minecraft:beetroot_soup", "minecraft:bowl"]
	MaidEatenReturnContainerList = []
	#Recognition distance of a maid under the gun task, Suitable for sniper rifles
	#Range: 0 ~ 512
	MaidGunLongDistance = 64
	#Recognition distance of a maid under the gun task, Suitable for most types
	#Range: 0 ~ 512
	MaidGunMediumDistance = 48
	#Recognition distance of a maid under the gun task, Suitable for pistols and shotguns
	#Range: 0 ~ 512
	MaidGunNearDistance = 32
	#This is a global config that applies to all maids: how often maids speak
	#Range: 0 ~ 100
	GlobalMaidSoundFrequency = 100
	#This is a global config that applies to all maids: Whether or not to display chat bubbles
	GlobalMaidShowChatBubble = true
	#The max range of maid's bow attack
	#Range: 8 ~ 192
	BowRange = 48
	#The max range of maid's crossbow attack
	#Range: 8 ~ 192
	CrossbowRange = 64
	#The max range of maid's danmaku attack
	#Range: 8 ~ 192
	DanmakuRange = 64
	#The max range of maid's trident attack
	#Range: 8 ~ 192
	TridentRange = 48

[chair]
	#Chair can switch models freely
	ChairChangeModel = true
	#Chair can be destroyed by anyone
	ChairCanDestroyedByAnyone = true

[misc]
	#Maid fairy's power point
	#Range: 0.0 ~ 5.0
	MaidFairyPowerPoint = 0.16
	#Maid fairy's spawn probability (zombie is 100, enderman is 10)
	#Range: > 0
	MaidFairySpawnProbability = 70
	#The following dimension do not spawn maid fairy
	MaidFairyBlacklistDimension = ["minecraft:the_nether", "minecraft:the_end", "twilightforest:twilight_forest"]
	#Loss power point after player death
	#Range: 0.0 ~ 5.0
	PlayerDeathLossPowerPoint = 1.0
	#Give a soul spell item for player first join
	GiveSoulSpell = true
	#Give the Memorizable Gensokyo book item for player first join
	GivePatchouliBook = true
	#Shrine Lamp Effect Cost (Power Point/Per Hour)
	#Range: 0.0 ~ 1.7976931348623157E308
	ShrineLampEffectCost = 0.9
	#Shrine Lamp Max Storage Power Point
	#Range: 0.0 ~ 1.7976931348623157E308
	ShrineLampMaxStorage = 100.0
	#Shrine Lamp Max Range Of Absorb Power Point
	#Range: > 0
	ShrineLampMaxRange = 6
	#Whether to turn off the Optifine warning
	CloseOptifineWarning = false
	#The range of the scarecrow to prevent the fairy maid from spawning
	#Range: > 0
	ScarecrowRange = 48
	#Whether to use the new version of the Fairy Maid model
	UseNewMaidFairyModel = true
	#Whether to enable model icon caching
	EnableModelIconCache = false
	#Does an invulnerable maid have a particle effect?
	InvulnerableParticleEffect = true

[vanilla]
	#Whether to replace the vanilla slime model with the yukkuri.
	ReplaceSlimeModel = true
	#Whether to replace the vanilla xp orb texture with the point items.
	ReplaceXPTexture = true
	#Whether to replace the vanilla totem texture with the life point.
	ReplaceTotemTexture = true
	#Whether to replace the vanilla bottle of xp texture with the point items.
	ReplaceXPBottleTexture = true

[render]
	EnableCompassTip = true
	EnableGoldenAppleTip = true
	EnablePotionTip = true
	EnableMilkBucketTip = true
	EnableGlassBottleTip = true
	EnableNameTagTip = true
	EnableLeadTip = true
	EnableSaddleTip = true
	EnableShearsTip = true

[ai]
	#Whether or not to enable the AI LLM feature
	LLMEnabled = true
	#LLM temperature, the higher this value, the more random the output will be
	#Range: 0.0 ~ 2.0
	LLMTemperature = 0.7
	#Whether to enable the function call function?
	#The maid will be able to interact with the game after it is enabled, but it will increase the amount of token used
	FunctionCallEnable = false
	#Whether to automatically generate the maid's settings
	AutoGenSettingEnabled = true
	#LLM AI Proxy Address, such as 127.0.0.1:1080, empty is no proxy, SOCKS proxies are not supported
	LLMProxyAddress = ""
	#The maximum token supported by the LLM AI
	#Range: > 1
	LLMMaxToken = 4096
	#The maximum historical conversation length cached by the maid
	#Range: 1 ~ 128
	MaidMaxHistoryLLMSize = 16
	#The maximum tokens that a player can use
	#Range: > 1
	MaxTokensPerPlayer = 2147483647
	#Whether or not to enable the TTS feature
	TTSEnabled = true
	#The TTS language you intend to use, will be overridden by the maid's settings
	TTSLanguage = "en_us"
	#TTS Proxy Address, such as 127.0.0.1:1080, empty is no proxy, SOCKS proxies are not supported
	TTSProxyAddress = ""
	#Whether or not to enable the STT feature
	STTEnabled = true
	#STT Type, currently support player2 app or aliyun
	#Allowed Values: PLAYER2, ALIYUN, SILICONFLOW
	STTType = "PLAYER2"
	#The name of the microphone device, empty is default
	STTMicrophone = ""
	#The range of search when chatting with the maid
	#Range: 1 ~ 256
	MaidCanChatDistance = 12
	#STT Proxy Address, such as 127.0.0.1:1080, empty is no proxy, SOCKS proxies are not supported
	STTProxyAddress = ""

