
["充能强化"]
	#充能强化 特性使用的物品, 默认: "minecraft:bedrock"
	"使用的物品" = "minecraft:bedrock"
	#充能强化 特性攻击增益, 0.1代表10%额外伤害, 默认: 0.1
	#Range: 0.0 ~ 10.0
	"增益" = 0.1

["远射"]
	#远射 特性伤害系数, 1.0代表最终伤害*1, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"系数" = 1.0

["高地"]
	#高地 特性伤害系数, 1.0代表最终伤害*1, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"系数" = 1.0

["冲击"]
	#冲击 特性水平击退系数, 1.0代表最终水平击退力度*1, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"水平系数" = 1.0
	#冲击 特性垂直击退系数, 1.0代表最终垂直击退力度*1, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"垂直系数" = 1.0

["饱和"]
	#饱和 特性攻击增益, 0.2代表20%额外伤害, 默认: 0.2
	#Range: 0.0 ~ 10.0
	"增益" = 0.2
	#饱和 特性血量百分比阈值, 0.8代表80%血量以上, 默认: 0.8
	#Range: 0.0 ~ 1.0
	"阈值" = 0.8

["破釜沉舟"]
	#破釜沉舟 特性攻击增益, 0.2代表20%额外伤害, 默认: 0.2
	#Range: 0.0 ~ 10.0
	"增益" = 0.2
	#破釜沉舟 特性血量百分比阈值, 0.3代表代表30%血量以下, 默认: 0.3
	#Range: 0.0 ~ 1.0
	"阈值" = 0.3

["连击"]
	#连击 特性攻击增益, 0.03代表每段3%额外伤害, 默认: 0.03
	#Range: 0.0 ~ 1.0
	"增益" = 0.03
	#连击 特性攻击段数, 5代表最高五段, 默认: 5
	#Range: 1 ~ 100
	"段数" = 5
	#连击 特性是否因为受伤清零, true代表清零, 默认: true
	"是/否" = true

["同调"]
	#同调 特性生效的物品, 默认: "minecraft:barrier"
	"生效的物品" = "minecraft:barrier"
	#同调 特性修补收益, 0.025代表每个物品每秒修复0.025耐久值, 默认: 0.025
	#Range: 0.0 ~ 1.0
	"增益" = 0.025
	#同调 特性生效物品数量上限, 64代表最高64个物品, 默认: 64
	#Range: 1 ~ 100
	"数量" = 64

["荣耀"]
	#荣耀 特性给予村庄英雄的时长, 单位为分钟, 默认: 30
	#Range: 1 ~ 60
	"时长" = 30
	#荣耀 特性给予村庄英雄时消耗的耐久, 默认: 100
	#Range: 0 ~ 1000
	"消耗耐久" = 100
	#荣耀 特性给予村庄英雄的上限等级, 默认: 5
	#Range: 1 ~ 255
	"等级" = 5
	#荣耀 特性是否逐级提升至最高等级, 若为否则一次性给予最高等级, 默认: 是
	"是/否" = true

["邪念"]
	#邪念 特性给予不祥之兆的时长, 单位为分钟, 默认: 5
	#Range: 1 ~ 60
	"时长" = 5
	#邪念 特性给予不祥之兆时消耗的耐久, 默认: 100
	#Range: 0 ~ 1000
	"消耗耐久" = 100
	#邪念 特性给予不祥之兆的上限等级, 默认: 5
	#Range: 1 ~ 255
	"等级" = 5
	#邪念 特性是否逐级提升至最高等级, 若为否则一次性给予最高等级, 默认: 是
	"是/否" = true

["经验收割(只有最高等级生效)"]
	#经验收割一级 特性给予的经验增益, 0.2代表20%额外经验, 默认: 0.2
	#Range: 0.0 ~ 10.0
	"一级增益" = 0.2
	#经验收割二级 特性给予的经验增益, 0.5代表50%额外经验, 默认: 0.5
	#Range: 0.0 ~ 10.0
	"二级增益" = 0.5
	#经验收割三级 特性给予的经验增益, 1.0代表100%额外经验, 默认: 1.0
	#Range: 0.0 ~ 10.0
	"三级增益" = 1.0

["幻影侵袭"]
	#幻影侵袭 特性追加箭矢的轮次数, 5代表5轮箭矢, 默认: 5
	#Range: 0 ~ 9
	"轮次数" = 5
	#幻影侵袭 特性追加箭矢的基础伤害, 8.0代表箭矢基础伤害为8.0, 默认: 8.0
	#Range: 0.0 ~ 32767.0
	"基础伤害" = 8.0
	#幻影侵袭 特性每轮追加箭矢的箭矢数, 1代表箭矢数为1, 默认: 1
	#Range: 0 ~ 5
	"每轮箭矢数" = 1

["幻影狂澜"]
	#幻影狂澜 特性追加箭矢的轮次数, 3代表3轮箭矢, 默认: 3
	#Range: 0 ~ 9
	"轮次数" = 3
	#幻影狂澜 特性箭雨箭矢的基础伤害, 4.0代表箭矢基础伤害为4.0, 默认: 4.0
	#Range: 0.0 ~ 32767.0
	"基础伤害" = 4.0
	#幻影狂澜 特性每轮箭雨的箭矢数, 8代表箭矢数为8, 默认: 8
	#Range: 0 ~ 30
	"每轮箭矢数" = 8

["幻影箭雨"]
	#幻影箭雨 特性箭雨箭矢的基础伤害, 5.0代表箭矢基础伤害为5.0, 默认: 5.0
	#Range: 0.0 ~ 32767.0
	"基础伤害" = 5.0
	#幻影箭雨 特性每轮箭雨的箭矢数, 12代表箭矢数为12, 默认: 12
	#Range: 0 ~ 30
	"每轮箭矢数" = 12

["居合连斩"]
	#居合连斩 特性造成的伤害, 10.0代表基础伤害为10.0, 默认: 10.0
	#Range: 0.0 ~ 32767.0
	"基础伤害" = 10.0

